[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqDifferentiation = "4302a76b-040a-498a-8c04-15b101fed76b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TrixiParticles = "66699cd8-9c01-4e9d-a059-b96c86d16b3a"
